/*
 * Copyright 2026 SorrowBlue
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sorrowblue.kioarch

import kotlinx.io.files.Path
import kotlinx.io.Sink

// Global map to track active Kotlin objects passed to C callbacks
private val opaqueMap = mutableMapOf<Int, Any>()
private var nextOpaqueId = 1

@JsName("registerOpaque")
internal fun registerOpaque(obj: Any): Int {
    val id = nextOpaqueId++
    opaqueMap[id] = obj
    return id
}

@JsName("getOpaque")
internal fun getOpaque(id: Int): Any? = opaqueMap[id]

@JsName("releaseOpaque")
internal fun releaseOpaque(id: Int) {
    opaqueMap.remove(id)
}

// Emscripten JavaScript module interface
private var wasmModule: dynamic = null

private fun wasmUtf8ToString(wasm: dynamic, namePtr: Int): String {
    val decoder = js("""
        function(wasm, namePtr) {
            var len = 0;
            while (wasm.HEAPU8[namePtr + len] !== 0) {
                len++;
            }
            if (len === 0) return "";
            var bytes = new Uint8Array(wasm.HEAPU8.buffer, namePtr, len);
            try {
                var utf8Decoder = new TextDecoder('utf-8', { fatal: true });
                return utf8Decoder.decode(bytes);
            } catch (e) {
                try {
                    var sjisDecoder = new TextDecoder('shift-jis');
                    return sjisDecoder.decode(bytes);
                } catch (err) {
                    return wasm.UTF8ToString(namePtr);
                }
            }
        }
    """) as (dynamic, Int) -> String
    return decoder(wasm, namePtr)
}

private fun bridgeRead(wasm: dynamic, source: Any, bufPtr: Int, len: Int): Int {
    val innerSource = source as? SeekableSource ?: return -1
    return try {
        val tmpArray = ByteArray(len)
        val bytesRead = innerSource.read(tmpArray, 0, len)
        if (bytesRead > 0) {
            val jsArray = tmpArray.asDynamic() as org.khronos.webgl.Int8Array
            val view = org.khronos.webgl.Uint8Array(jsArray.buffer, jsArray.byteOffset, bytesRead)
            wasm.HEAPU8.set(view, bufPtr)
        }
        bytesRead
    } catch (e: Throwable) {
        -1
    }
}

private fun bridgeSeek(source: Any, pos: Double) {
    try {
        (source as? SeekableSource)?.seek(pos.toLong())
    } catch (e: Throwable) {
        // Safe guard to prevent throwing into C++ Wasm boundary
    }
}

private fun bridgePosition(source: Any): Double {
    return try {
        (source as? SeekableSource)?.position()?.toDouble() ?: 0.0
    } catch (e: Throwable) {
        0.0
    }
}

private fun bridgeLength(source: Any): Double {
    return try {
        (source as? SeekableSource)?.length()?.toDouble() ?: 0.0
    } catch (e: Throwable) {
        0.0
    }
}

private fun bridgeWrite(wasm: dynamic, sink: Any, bufPtr: Int, len: Int) {
    val innerSink = sink as? Sink ?: return
    try {
        val tmpArray = ByteArray(len)
        val jsArray = tmpArray.asDynamic() as org.khronos.webgl.Int8Array
        val view = org.khronos.webgl.Int8Array(wasm.HEAPU8.buffer as org.khronos.webgl.ArrayBuffer, bufPtr, len)
        jsArray.set(view)
        innerSink.write(tmpArray, 0, len)
    } catch (e: Throwable) {
        // Safe guard to prevent throwing into C++ Wasm boundary
    }
}

/**
 * JS implementation of [KioArch] utilizing WebAssembly compiled from pure C archive engines.
 */
public actual object KioArch {

    /**
     * Initializes the WebAssembly module wrapper generated by Emscripten.
     * This MUST be called and completed before using any archive operations.
     *
     * @param module the modularized Emscripten Module instance
     */
    public fun initialize(module: Any) {
        wasmModule = module
    }

    /**
     * Creates an [ArchiveReader] from a custom [SeekableSource] for JS.
     *
     * @param source the seekable source containing the archive data
     * @return an [ArchiveReader] to read the archive
     * @throws ArchiveException if native library fails to open the archive
     */
    public actual fun createReader(source: SeekableSource): ArchiveReader {
        val wasm = wasmModule ?: throw IllegalStateException("KioArch has not been initialized. Call KioArch.initialize(module) first.")
        
        val sourceOpaqueId = registerOpaque(source)
        var sourcePtr = 0
        var readFuncPtr = 0
        var seekFuncPtr = 0
        var posFuncPtr = 0
        var lenFuncPtr = 0
        var handle: Long = 0L

        try {
            // Register callbacks to Emscripten function table
            val readFuncCreator = js("""
                function(wasm, getOpaque, bridgeRead) {
                    return wasm.addFunction(function(opaqueId, bufPtr, len) {
                        var innerSource = getOpaque(opaqueId);
                        if (!innerSource) return -1;
                        return bridgeRead(wasm, innerSource, bufPtr, len);
                    }, 'iiii');
                }
            """) as (dynamic, (Int) -> Any?, (dynamic, Any, Int, Int) -> Int) -> Int
            readFuncPtr = readFuncCreator(wasm, ::getOpaque, ::bridgeRead)

            val seekFuncCreator = js("""
                function(wasm, getOpaque, bridgeSeek) {
                    return wasm.addFunction(function(opaqueId, pos) {
                        var innerSource = getOpaque(opaqueId);
                        if (innerSource) {
                            bridgeSeek(innerSource, Number(pos));
                        }
                    }, 'vij');
                }
            """) as (dynamic, (Int) -> Any?, (Any, Double) -> Unit) -> Int
            seekFuncPtr = seekFuncCreator(wasm, ::getOpaque, ::bridgeSeek)

            val posFuncCreator = js("""
                function(wasm, getOpaque, bridgePosition) {
                    return wasm.addFunction(function(opaqueId) {
                        var innerSource = getOpaque(opaqueId);
                        var bigInt = globalThis["BigInt"];
                        return innerSource ? bigInt(bridgePosition(innerSource)) : bigInt(0);
                    }, 'ji');
                }
            """) as (dynamic, (Int) -> Any?, (Any) -> Double) -> Int
            posFuncPtr = posFuncCreator(wasm, ::getOpaque, ::bridgePosition)

            val lenFuncCreator = js("""
                function(wasm, getOpaque, bridgeLength) {
                    return wasm.addFunction(function(opaqueId) {
                        var innerSource = getOpaque(opaqueId);
                        var bigInt = globalThis["BigInt"];
                        return innerSource ? bigInt(bridgeLength(innerSource)) : bigInt(0);
                    }, 'ji');
                }
            """) as (dynamic, (Int) -> Any?, (Any) -> Double) -> Int
            lenFuncPtr = lenFuncCreator(wasm, ::getOpaque, ::bridgeLength)

            // Allocate and populate kio_source_t structure (20 bytes)
            sourcePtr = wasm._malloc(20) as Int
            val heap32 = wasm.HEAP32
            val sourceWordOffset = sourcePtr / 4
            heap32[sourceWordOffset + 0] = readFuncPtr
            heap32[sourceWordOffset + 1] = seekFuncPtr
            heap32[sourceWordOffset + 2] = posFuncPtr
            heap32[sourceWordOffset + 3] = lenFuncPtr
            heap32[sourceWordOffset + 4] = sourceOpaqueId

            // Allocate error message buffer (512 bytes)
            val errMsgPtr = wasm._malloc(512) as Int
            try {
                val rawHandle = wasm._kio_open_archive(sourcePtr, errMsgPtr, 512)
                
                // Emscripten handles 64-bit unsigned int returns as BigInt or low/high parts.
                // In modern Emscripten with BigInt support, it is returned as a BigInt.
                val handleVal = (js("function(raw) { return globalThis['BigInt'](raw); }") as (dynamic) -> dynamic)(rawHandle)
                val isZero = (js("function(raw) { return globalThis['BigInt'](raw) === globalThis['BigInt'](0); }") as (dynamic) -> Boolean)(rawHandle)
                if (isZero) {
                    // Extract error message
                    val errMsg = wasmUtf8ToString(wasm, errMsgPtr)
                    throw ArchiveIOException("Failed to open archive. Native error: $errMsg")
                }
                handle = handleVal.toString().toLong()
            } finally {
                wasm._free(errMsgPtr)
            }

            return JsArchiveReader(wasm, sourceOpaqueId, sourcePtr, readFuncPtr, seekFuncPtr, posFuncPtr, lenFuncPtr, handle)
        } catch (e: Exception) {
            // Clean up resources on failure
            if (sourcePtr != 0) wasm._free(sourcePtr)
            if (readFuncPtr != 0) wasm.removeFunction(readFuncPtr)
            if (seekFuncPtr != 0) wasm.removeFunction(seekFuncPtr)
            if (posFuncPtr != 0) wasm.removeFunction(posFuncPtr)
            if (lenFuncPtr != 0) wasm.removeFunction(lenFuncPtr)
            releaseOpaque(sourceOpaqueId)
            throw e
        }
    }

    /**
     * Creates an [ArchiveReader] from an in-memory [ByteArray] for JS.
     *
     * @param byteArray the byte array containing the archive data
     * @return an [ArchiveReader] to read the archive
     * @throws ArchiveException if native library fails to open the archive
     */
    public actual fun createReader(byteArray: ByteArray): ArchiveReader {
        return createReader(ByteArraySeekableSource(byteArray))
    }

    /**
     * Creates an [ArchiveReader] from a Kotlin Multiplatform [Path] for JS.
     *
     * @param path the path to the archive file
     * @return an [ArchiveReader] to read the archive
     * @throws ArchiveException if native library fails to open the archive
     */
    public actual fun createReader(path: Path): ArchiveReader {
        if (isNodeJs()) {
            return createReader(NodeFileSeekableSource(path.toString()))
        }
        throw UnsupportedOperationException("File system access using Path is not supported in browser JS environment. Use ByteArray or custom SeekableSource.")
    }
}

private fun isNodeJs(): Boolean {
    return js("typeof process !== 'undefined' && process.versions != null && process.versions.node != null") as Boolean
}

private class NodeFileSeekableSource(private val pathStr: String) : SeekableSource {
    private val fs: dynamic = js("require('fs')")
    private val fd: Int
    private var pos: Long = 0L
    private val totalLength: Long

    init {
        fd = fs.openSync(pathStr, "r") as Int
        val stats = fs.fstatSync(fd)
        totalLength = (stats.size as Double).toLong()
    }

    override fun read(buffer: ByteArray, offset: Int, length: Int): Int {
        if (pos >= totalLength) return -1
        val bytesToRead = minOf(length.toLong(), totalLength - pos).toInt()
        if (bytesToRead <= 0) return 0

        val jsBuffer = if (js("typeof Buffer.alloc === 'function'") as Boolean) js("Buffer.alloc(bytesToRead)") else js("new Buffer(bytesToRead)")
        val readBytes = fs.readSync(fd, jsBuffer, 0, bytesToRead, pos.toDouble()) as Int
        if (readBytes <= 0) return -1

        val kotlinArray = buffer.asDynamic() as org.khronos.webgl.Int8Array
        val view = org.khronos.webgl.Int8Array(jsBuffer.buffer as org.khronos.webgl.ArrayBuffer, jsBuffer.byteOffset as Int, readBytes)
        kotlinArray.set(view, offset)

        pos += readBytes
        return readBytes
    }

    override fun seek(position: Long) {
        pos = maxOf(0L, minOf(position, totalLength))
    }

    override fun position(): Long = pos

    override fun length(): Long = totalLength

    override fun close() {
        fs.closeSync(fd)
    }
}

private class JsArchiveReader(
    private val wasm: dynamic,
    private val sourceOpaqueId: Int,
    private val sourcePtr: Int,
    private val readFuncPtr: Int,
    private val seekFuncPtr: Int,
    private val posFuncPtr: Int,
    private val lenFuncPtr: Int,
    private val handle: Long
) : ArchiveReader {

    private var isClosed = false

    override fun getEntries(): List<ArchiveEntry> {
        if (isClosed) throw IllegalStateException("Reader is closed")
        
        // Emscripten receives Long as BigInt
        val rawHandle = (js("function(h) { return globalThis['BigInt'](h.toString()); }") as (dynamic) -> dynamic)(handle)
        val count = wasm._kio_get_entry_count(rawHandle) as Int
        if (count < 0) return emptyList()

        val list = ArrayList<ArchiveEntry>(count)
        // Allocate kio_entry_t (24 bytes)
        val entryPtr = wasm._malloc(24) as Int
        try {
            for (i in 0 until count) {
                if (wasm._kio_get_entry(rawHandle, i, entryPtr) as Int != 0) {
                    val heap32 = wasm.HEAP32
                    val wordOffset = entryPtr / 4
                    val index = heap32[wordOffset + 0] as Int
                    val namePtr = heap32[wordOffset + 1] as Int
                    
                    // Read string from memory using Emscripten helper
                    val nameStr = wasmUtf8ToString(wasm, namePtr)
                    val normalizedName = nameStr.replace('\\', '/')

                    // Size is int64, read from HEAP64/HEAPU32
                    // Emscripten handles 64-bit alignment, so offset of size is 8 bytes (word offset 2 and 3)
                    val sizeVal = (js("function(heap, idx) { return Number(heap[idx]); }") as (dynamic, Int) -> Double)(wasm.HEAP64, (entryPtr + 8) / 8)
                    val size = sizeVal.toLong()

                    val isDir = heap32[wordOffset + 4] as Int != 0
                    val crc = heap32[wordOffset + 5] as Int

                    list.add(
                        ArchiveEntry(
                            index = index,
                            name = normalizedName,
                            size = size,
                            compressedSize = size,
                            isDirectory = isDir,
                            crc = crc.toLong() and 0xFFFFFFFFL
                        )
                    )
                }
            }
        } finally {
            wasm._free(entryPtr)
        }
        return list
    }

    override fun extractEntry(entry: ArchiveEntry, sink: Sink) {
        if (isClosed) throw IllegalStateException("Reader is closed")
        
        val sinkOpaqueId = registerOpaque(sink)
        var sinkPtr = 0
        var writeFuncPtr = 0
        
        try {
            val writeFuncCreator = js("""
                function(wasm, getOpaque, bridgeWrite) {
                    return wasm.addFunction(function(opaqueId, bufPtr, len) {
                        var innerSink = getOpaque(opaqueId);
                        if (innerSink) {
                            bridgeWrite(wasm, innerSink, bufPtr, len);
                        }
                    }, 'viii');
                }
            """) as (dynamic, (Int) -> Any?, (dynamic, Any, Int, Int) -> Unit) -> Int
            writeFuncPtr = writeFuncCreator(wasm, ::getOpaque, ::bridgeWrite)

            // Allocate kio_sink_t (8 bytes)
            sinkPtr = wasm._malloc(8) as Int
            val heap32 = wasm.HEAP32
            val wordOffset = sinkPtr / 4
            heap32[wordOffset + 0] = writeFuncPtr
            heap32[wordOffset + 1] = sinkOpaqueId

            val rawHandle = (js("function(h) { return globalThis['BigInt'](h.toString()); }") as (dynamic) -> dynamic)(handle)
            val errMsgPtr = wasm._malloc(512) as Int
            try {
                val success = wasm._kio_extract_entry(
                    rawHandle,
                    entry.index,
                    sinkPtr,
                    errMsgPtr,
                    512
                ) as Int

                if (success == 0) {
                    val errMsg = wasmUtf8ToString(wasm, errMsgPtr)
                    throw ArchiveIOException("Failed to extract entry: ${entry.name}. Native error: $errMsg")
                }
            } finally {
                wasm._free(errMsgPtr)
            }
        } finally {
            if (sinkPtr != 0) wasm._free(sinkPtr)
            if (writeFuncPtr != 0) wasm.removeFunction(writeFuncPtr)
            releaseOpaque(sinkOpaqueId)
        }
    }

    override fun close() {
        if (!isClosed) {
            val rawHandle = (js("function(h) { return globalThis['BigInt'](h.toString()); }") as (dynamic) -> dynamic)(handle)
            wasm._kio_close_archive(rawHandle)
            wasm._free(sourcePtr)
            wasm.removeFunction(readFuncPtr)
            wasm.removeFunction(seekFuncPtr)
            wasm.removeFunction(posFuncPtr)
            wasm.removeFunction(lenFuncPtr)
            releaseOpaque(sourceOpaqueId)
            isClosed = true
        }
    }
}
