/*
 * Copyright 2026 SorrowBlue
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sorrowblue.kioarch

import kotlinx.io.Sink
import kotlinx.io.files.Path

// Global reference to track active Wasm module instance
private var wasmModule: JsAny? = null

private const val SOURCE_STRUCT_SIZE = 20
private const val ENTRY_STRUCT_SIZE = 24
private const val SINK_STRUCT_SIZE = 8
private const val ERR_MSG_BUFFER_SIZE = 512
private const val ENTRY_SIZE_OFFSET = 1

private class WasmSourceCallbackPtrs(
    val readPtr: Int,
    val seekPtr: Int,
    val posPtr: Int,
    val lenPtr: Int
)

private fun throwNotInitializedWasm(): Nothing {
    throw IllegalStateException(
        "KioArch has not been initialized. Call KioArch.initialize(module) first."
    )
}

private fun registerWasmSourceCallbacks(module: JsAny): WasmSourceCallbackPtrs {
    val readPtr = registerReadCallback(module)
    val seekPtr = registerSeekCallback(module)
    val posPtr = registerPosCallback(module)
    val lenPtr = registerLenCallback(module)
    return WasmSourceCallbackPtrs(readPtr, seekPtr, posPtr, lenPtr)
}

private fun cleanupWasmSourcePtrs(
    module: JsAny,
    sourcePtr: Int,
    ptrs: WasmSourceCallbackPtrs?,
    opaqueId: Int
) {
    if (sourcePtr != 0) wasmFree(module, sourcePtr)
    if (ptrs != null) {
        if (ptrs.readPtr != 0) wasmRemoveFunction(module, ptrs.readPtr)
        if (ptrs.seekPtr != 0) wasmRemoveFunction(module, ptrs.seekPtr)
        if (ptrs.posPtr != 0) wasmRemoveFunction(module, ptrs.posPtr)
        if (ptrs.lenPtr != 0) wasmRemoveFunction(module, ptrs.lenPtr)
    }
    removeSourceJs(opaqueId)
    releaseOpaque(opaqueId)
}

private fun copyToHeap(module: JsAny, bufPtr: Int, byteArray: ByteArray, len: Int) {
    copyToHeapJs(module, bufPtr, getByteFn = { i -> byteArray[i] }, len)
}

private fun copyFromHeap(module: JsAny, bufPtr: Int, byteArray: ByteArray, len: Int) {
    copyFromHeapJs(module, bufPtr, setByteFn = { i, value -> byteArray[i] = value }, len)
}

// Global map to track active Kotlin objects passed to C callbacks for Wasm
private val opaqueMap = mutableMapOf<Int, Any>()
private var nextOpaqueId = 1

private fun registerOpaque(obj: Any): Int {
    val id = nextOpaqueId++
    opaqueMap[id] = obj
    return id
}

private fun getOpaque(id: Int): Any? = opaqueMap[id]

private fun releaseOpaque(id: Int) {
    opaqueMap.remove(id)
}

/**
 * WasmJs implementation of [KioArch] utilizing WebAssembly compiled from pure C archive engines.
 */
public actual object KioArch {

    /**
     * Initializes the WebAssembly module wrapper generated by Emscripten.
     * This MUST be called and completed before using any archive operations.
     *
     * @param module the modularized Emscripten Module instance
     */
    public fun initialize(module: Any) {
        wasmModule = module.cast()
        initOpaqueMap()
        initSinkMap()
    }

    /**
     * Creates an [ArchiveReader] from a custom [SeekableSource] for WasmJs.
     *
     * @param source the seekable source containing the archive data
     * @return an [ArchiveReader] to read the archive
     * @throws ArchiveException if native library fails to open the archive
     */
    public actual fun createReader(source: SeekableSource): ArchiveReader {
        val module = wasmModule ?: throwNotInitializedWasm()

        val sourceOpaqueId = registerOpaque(source)
        var sourcePtr = 0
        var ptrs: WasmSourceCallbackPtrs? = null
        var handle: JsAny? = null

        try {
            // Register Kotlin SeekableSource callbacks into JS global map
            putWasmSourceCallbacks(module, sourceOpaqueId)

            // Register C-compatible callback function pointers in Emscripten
            ptrs = registerWasmSourceCallbacks(module)

            // Allocate and populate kio_source_t structure (20 bytes)
            sourcePtr = wasmMalloc(module, SOURCE_STRUCT_SIZE)
            writeHeap32(module, sourcePtr, 0, ptrs.readPtr)
            writeHeap32(module, sourcePtr, 1, ptrs.seekPtr)
            writeHeap32(module, sourcePtr, 2, ptrs.posPtr)
            writeHeap32(module, sourcePtr, 3, ptrs.lenPtr)
            writeHeap32(module, sourcePtr, 4, sourceOpaqueId)

            // Allocate error message buffer (512 bytes)
            val errMsgPtr = wasmMalloc(module, ERR_MSG_BUFFER_SIZE)
            try {
                val rawHandle = wasmOpenArchive(module, sourcePtr, errMsgPtr, ERR_MSG_BUFFER_SIZE)
                val handleVal = toBigInt(rawHandle)

                if (isZeroBigInt(handleVal)) {
                    val errMsg = wasmUtf8ToString(module, errMsgPtr)
                    throw ArchiveIOException("Failed to open archive. Native error: $errMsg")
                }
                handle = handleVal
            } finally {
                wasmFree(module, errMsgPtr)
            }

            return WasmArchiveReader(
                module,
                sourceOpaqueId,
                sourcePtr,
                ptrs.readPtr,
                ptrs.seekPtr,
                ptrs.posPtr,
                ptrs.lenPtr,
                handle
            )
        } catch (e: Exception) {
            cleanupWasmSourcePtrs(module, sourcePtr, ptrs, sourceOpaqueId)
            throw e
        }
    }

    /**
     * Creates an [ArchiveReader] from an in-memory [ByteArray] for WasmJs.
     *
     * @param byteArray the byte array containing the archive data
     * @return an [ArchiveReader] to read the archive
     * @throws ArchiveException if native library fails to open the archive
     */
    public actual fun createReader(byteArray: ByteArray): ArchiveReader =
        createReader(ByteArraySeekableSource(byteArray))

    /**
     * Creates an [ArchiveReader] from a Kotlin Multiplatform [Path] for WasmJs.
     *
     * @param path the path to the archive file
     * @return an [ArchiveReader] to read the archive
     * @throws ArchiveException if native library fails to open the archive
     */
    public actual fun createReader(path: Path): ArchiveReader {
        if (isNodeJsWasm()) {
            val module = wasmModule ?: throw IllegalStateException(
                "KioArch has not been initialized. Call KioArch.initialize(module) first."
            )
            return createReader(NodeFileSeekableSource(path.toString(), module))
        }
        throw UnsupportedOperationException(
            "File system access using Path is not supported in browser WasmJs environment. Use ByteArray or custom SeekableSource."
        )
    }
}

@Suppress("SwallowedException", "TooGenericExceptionCaught")
private fun putWasmSourceCallbacks(module: JsAny, sourceOpaqueId: Int) {
    putSourceJs(
        sourceOpaqueId,
        readFn = { bufPtr, len ->
            val innerSource = getOpaque(sourceOpaqueId) as? SeekableSource
            if (innerSource == null) {
                -1
            } else {
                try {
                    val tmpArray = ByteArray(len)
                    val readBytes = innerSource.read(tmpArray, 0, len)
                    if (readBytes > 0) {
                        copyToHeap(module, bufPtr, tmpArray, readBytes)
                    }
                    readBytes
                } catch (e: Throwable) {
                    -1
                }
            }
        },
        seekFn = { pos ->
            try {
                val innerSource = getOpaque(sourceOpaqueId) as? SeekableSource
                innerSource?.seek(pos.toLong())
            } catch (e: Throwable) {
                // Safe guard to prevent throwing into C++ Wasm boundary
            }
        },
        posFn = {
            try {
                val innerSource = getOpaque(sourceOpaqueId) as? SeekableSource
                innerSource?.position()?.toDouble() ?: 0.0
            } catch (e: Throwable) {
                0.0
            }
        },
        lenFn = {
            try {
                val innerSource = getOpaque(sourceOpaqueId) as? SeekableSource
                innerSource?.length()?.toDouble() ?: 0.0
            } catch (e: Throwable) {
                0.0
            }
        }
    )
}

private class NodeFileSeekableSource(private val pathStr: String, private val module: JsAny) :
    SeekableSource {
    private val fd: Int
    private var pos: Long = 0L
    private val totalLength: Long

    init {
        initNodeFs()
        fd = nodeOpenSync(pathStr)
        if (fd < 0) throw ArchiveIOException("Failed to open file: $pathStr")
        totalLength = nodeSizeSync(fd).toLong()
    }

    override fun read(buffer: ByteArray, offset: Int, length: Int): Int {
        val result: Int
        if (pos >= totalLength) {
            result = -1
        } else {
            val bytesToRead = minOf(length.toLong(), totalLength - pos).toInt()
            if (bytesToRead <= 0) {
                result = 0
            } else {
                val readBytes = nodeReadSync(
                    fd,
                    0,
                    bytesToRead,
                    pos.toDouble(),
                    module,
                    copyFn = { i, value ->
                        buffer[offset + i] = value
                    }
                )
                if (readBytes > 0) {
                    pos += readBytes
                }
                result = readBytes
            }
        }
        return result
    }

    override fun seek(position: Long) {
        pos = maxOf(0L, minOf(position, totalLength))
    }

    override fun position(): Long = pos

    override fun length(): Long = totalLength

    override fun close() {
        nodeCloseSync(fd)
    }
}

private class WasmArchiveReader(
    private val module: JsAny,
    private val sourceOpaqueId: Int,
    private val sourcePtr: Int,
    private val readFuncPtr: Int,
    private val seekFuncPtr: Int,
    private val posFuncPtr: Int,
    private val lenFuncPtr: Int,
    private val handle: JsAny
) : ArchiveReader {

    private var isClosed = false

    override fun getEntries(): List<ArchiveEntry> {
        if (isClosed) throw IllegalStateException("Reader is closed")

        val count = wasmGetEntryCount(module, handle)
        if (count < 0) return emptyList()

        val list = ArrayList<ArchiveEntry>(count)
        // Allocate kio_entry_t (24 bytes)
        val entryPtr = wasmMalloc(module, ENTRY_STRUCT_SIZE)
        try {
            for (i in 0 until count) {
                if (wasmGetEntry(module, handle, i, entryPtr) != 0) {
                    val index = readHeap32(module, entryPtr, 0)
                    val namePtr = readHeap32(module, entryPtr, 1)

                    val nameStr = wasmUtf8ToString(module, namePtr)
                    val normalizedName = nameStr.replace('\\', '/')

                    // Size is int64, read using double/HEAP64 helper (offset of size is 8 bytes)
                    val size = readHeap64Double(module, entryPtr, ENTRY_SIZE_OFFSET).toLong()

                    val isDir = readHeap32(module, entryPtr, 4) != 0
                    val crc = readHeap32(module, entryPtr, 5)

                    list.add(
                        ArchiveEntry(
                            index = index,
                            name = normalizedName,
                            size = size,
                            compressedSize = size,
                            isDirectory = isDir,
                            crc = crc.toLong() and 0xFFFFFFFFL
                        )
                    )
                }
            }
        } finally {
            wasmFree(module, entryPtr)
        }
        return list
    }

    override fun extractEntry(entry: ArchiveEntry, sink: Sink) {
        if (isClosed) throw IllegalStateException("Reader is closed")

        val sinkOpaqueId = registerOpaque(sink)
        var sinkPtr = 0
        var writeFuncPtr = 0

        try {
            // Register Kotlin Sink callback into JS global map
            putWasmSinkCallbacks(module, sinkOpaqueId)

            // Register C-compatible callback pointer in Emscripten
            writeFuncPtr = registerWriteCallback(module)

            // Allocate kio_sink_t (8 bytes)
            sinkPtr = wasmMalloc(module, SINK_STRUCT_SIZE)
            writeHeap32(module, sinkPtr, 0, writeFuncPtr)
            writeHeap32(module, sinkPtr, 1, sinkOpaqueId)

            val errMsgPtr = wasmMalloc(module, ERR_MSG_BUFFER_SIZE)
            try {
                val success = wasmExtractEntry(
                    module,
                    handle,
                    entry.index,
                    sinkPtr,
                    errMsgPtr,
                    ERR_MSG_BUFFER_SIZE
                )

                if (success == 0) {
                    val errMsg = wasmUtf8ToString(module, errMsgPtr)
                    throw ArchiveIOException(
                        "Failed to extract entry: ${entry.name}. Native error: $errMsg"
                    )
                }
            } finally {
                wasmFree(module, errMsgPtr)
            }
        } finally {
            if (sinkPtr != 0) wasmFree(module, sinkPtr)
            if (writeFuncPtr != 0) wasmRemoveFunction(module, writeFuncPtr)
            removeSinkJs(sinkOpaqueId)
            releaseOpaque(sinkOpaqueId)
        }
    }

    override fun close() {
        if (!isClosed) {
            wasmCloseArchive(module, handle)
            wasmFree(module, sourcePtr)
            wasmRemoveFunction(module, readFuncPtr)
            wasmRemoveFunction(module, seekFuncPtr)
            wasmRemoveFunction(module, posFuncPtr)
            wasmRemoveFunction(module, lenFuncPtr)
            removeSourceJs(sourceOpaqueId)
            releaseOpaque(sourceOpaqueId)
            isClosed = true
        }
    }
}

@Suppress("SwallowedException", "TooGenericExceptionCaught")
private fun putWasmSinkCallbacks(module: JsAny, sinkOpaqueId: Int) {
    putSinkJs(
        sinkOpaqueId,
        writeFn = { bufPtr, len ->
            val innerSink = getOpaque(sinkOpaqueId) as? Sink
            if (innerSink != null) {
                try {
                    val tmpArray = ByteArray(len)
                    copyFromHeap(module, bufPtr, tmpArray, len)
                    innerSink.write(tmpArray, 0, len)
                } catch (e: Throwable) {
                    // Safe guard to prevent throwing into C++ Wasm boundary
                }
            }
        }
    )
}

// Inline helper extension to cast JS reference safely in Kotlin/Wasm
@Suppress("UNCHECKED_CAST_TO_EXTERNAL_INTERFACE", "UNCHECKED_CAST")
private fun <T : JsAny> Any.cast(): T = this as T
