package com.sorrowblue.kioarch

import kotlin.js.ExperimentalWasmJsInterop
import kotlin.js.JsAny

@OptIn(ExperimentalWasmJsInterop::class)
public var wasmModule: JsAny? = null

/**
 * Initializes the WebAssembly module wrapper generated by Emscripten.
 * This MUST be called and completed before using any archive operations.
 *
 * @param module the modularized Emscripten Module instance
 */
public expect fun KioArch.initialize(module: Any)
