name: Lint
on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    strategy:
      matrix:
        include:
          - name: Detekt
            task: "reportMerge detektDebug detektDebugAndroidTest detektDebugUnitTest detektDeviceTestAndroid detektHostTestAndroid detektMain detektMainAndroid detektMainJvm detektRelease detektTest detektTestJvm --continue"
            sarif_file: "build/reports/detekt/merge.sarif"
            category: "detekt"
          - name: Detekt (build-logic)
            task: ":build-logic:detektMain"
            sarif_file: "build-logic/build/reports/detekt/main.sarif"
            category: "detekt"
    name: 🔍️ ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: recursive
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@0d6a7d60b009d01c9e7523be22153ff8f19460d3 # v2.2.0
        with:
          github-api-token: ${{ secrets.GITHUB_TOKEN }}
          cmake-version: '4.1.2'
      - name: Setup Emscripten (emsdk)
        uses: mymindstorm/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984 # v16
        with:
          version: '5.0.7'
      - name: Setup Java and Gradle
        uses: SorrowBlue/github-actions/.github/actions/setup-java-gradle@main
      - name: 🔍️Run analyze ${{ matrix.name }}
        run: ./gradlew ${{ matrix.task }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        if: ${{ !cancelled()}}
        with:
          sarif_file: ${{ matrix.sarif_file }}
          category: ${{ matrix.category }}
